name: '🦄 🌈  Aten Formulas'
description: 'Main collection of recipes for Drupal.'
type: 'Site'
recipes:
  - formula-foundational
  - formula-media
  - formula-paragraphs
  - formula-events
  - formula-news
